name: master-pipeline

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: marcusbalbi/udemy-docker-ci-example-complex-client:latest
      -
        name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: marcusbalbi/udemy-docker-ci-example-complex-nginx:latest
      -
        name: Build and push server
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: marcusbalbi/udemy-docker-ci-example-complex-server:latest
      -
        name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: ./worker
          push: true
          tags: marcusbalbi/udemy-docker-ci-example-complex-worker:latest
